### ISSUE TITLE
deploy has error: AttributeError: 'module' object has no attribute 'Http'

### ISSUE THREAD

**Issue by majidshokrolahi** [ocadotechnology/gcp-census#27]
I have followed all the step and I have deployed the app, but in the logs i see the following error:

`Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 96, in LoadObject
    __import__(cumulative_path)
  File "/base/data/home/apps/e~my-project-id/v2.407323645116515157/gcp_census/routes.py", line 3, in <module>
    from gcp_census.bigquery.bigquery_handler import BigQueryMainHandler, \
  File "/base/data/home/apps/e~my-project-id/v2.407323645116515157/gcp_census/bigquery/bigquery_handler.py", line 6, in <module>
    from gcp_census.bigquery.bigquery_client import BigQuery
  File "/base/data/home/apps/e~my-project-id/v2.407323645116515157/gcp_census/bigquery/bigquery_client.py", line 7, in <module>
    import googleapiclient.discovery
  File "/base/data/home/apps/e~my-project-id/v2.407323645116515157/lib/googleapiclient/discovery.py", line 71, in <module>
    from oauth2client.client import GoogleCredentials
  File "/base/data/home/apps/e~my-project-id/v2.407323645116515157/lib/oauth2client/client.py", line 1660, in <module>
    _cached_http = httplib2.Http(MemoryCache())
AttributeError: 'module' object has no attribute 'Http'`

 If I run the cron jobs (/bigQuery ) i see in logging the same error as bellow:

`(/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py:263)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 96, in LoadObject
    __import__(cumulative_path)
  File "/base/data/home/apps/e~my-project-id/v2.407323645116515157/gcp_census/routes.py", line 3, in <module>
    from gcp_census.bigquery.bigquery_handler import BigQueryMainHandler, \
  File "/base/data/home/apps/e~my-project-id/v2.407323645116515157/gcp_census/bigquery/bigquery_handler.py", line 6, in <module>
    from gcp_census.bigquery.bigquery_client import BigQuery
  File "/base/data/home/apps/e~my-project-id/v2.407323645116515157/gcp_census/bigquery/bigquery_client.py", line 7, in <module>
    import googleapiclient.discovery
  File "/base/data/home/apps/e~my-project-id/v2.407323645116515157/lib/googleapiclient/discovery.py", line 52, in <module>
    import httplib2
  File "/base/data/home/apps/e~my-project-id/v2.407323645116515157/lib/httplib2/__init__.py", line 352
    print('%s:' % h, end=' ', file=self._fp)
                        ^
SyntaxError: invalid syntax`

**Comment by marcin-kolda** [comment]
Hi @magicomajid,

It looks like some Python package issue.
Do you use virtualenv? Could you list all your Python dependencies (using `pip freeze`) and paste it here?

**Comment by majidshokrolahi** [comment]
Hi @marcin-kolda , I used virtualenv, and here is the Python dependencies:

>google-api-python-client==1.5.1
httplib2==0.10.3
oauth2client==2.2.0
pyasn1==0.2.3
pyasn1-modules==0.0.8
rsa==3.4.2
simplejson==3.13.2
six==1.11.0
uritemplate==0.6

Your help is appriciated

**Comment by marcin-kolda** [comment]
Please use new virtualenv, it should contain only packages used by gcp-census:
```
beautifulsoup4==4.6.0
funcsigs==1.0.2
google-api-python-client==1.5.1
httplib2==0.10.3
mock==2.0.0
nose-parameterized==0.5.0
oauth2client==2.2.0
pbr==3.0.1
pyasn1==0.2.3
pyasn1-modules==0.0.8
pycrypto==2.6.1
rsa==3.4.2
simplejson==3.10.0
six==1.10.0
uritemplate==0.6
waitress==1.0.2
WebOb==1.7.2
WebTest==2.0.23
```
Could you also let me know what are the contents of lib directory? It should be something like:
```
apiclient					pyasn1						simplejson-3.10.0.dist-info
google_api_python_client-1.5.1.dist-info	pyasn1-0.2.3.dist-info				six-1.10.0.dist-info
googleapiclient					pyasn1_modules					six.py
httplib2					pyasn1_modules-0.0.8.dist-info			six.pyc
httplib2-0.10.3.dist-info			rsa						uritemplate
oauth2client					rsa-3.4.2.dist-info				uritemplate-0.6.dist-info
oauth2client-2.2.0.dist-info			simplejson
```

**Comment by majidshokrolahi** [comment]
Actually I have redone everythings, so here is the list of lib folder: 
`__pycache__                               oauth2client-2.2.0.dist-info    simplejson
apiclient                                 pyasn1                          simplejson-3.13.2.dist-info
google_api_python_client-1.5.1.dist-info  pyasn1-0.2.3.dist-info          six-1.11.0.dist-info
googleapiclient                           pyasn1_modules                  six.py
httplib2                                  pyasn1_modules-0.0.8.dist-info  uritemplate
httplib2-0.10.3.dist-info                 rsa                             uritemplate-0.6.dist-info
oauth2client                              rsa-3.4.2.dist-info
`
and here is the result of pip freeze: 

> google-api-python-client==1.5.1
httplib2==0.10.3
oauth2client==2.2.0
pyasn1==0.2.3
pyasn1-modules==0.0.8
rsa==3.4.2
simplejson==3.13.2
six==1.11.0
uritemplate==0.6

**Comment by majidshokrolahi** [comment]
I have tried to install manually what were missing compering to the list you have written and here is the result: 

> beautifulsoup4==4.6.0
funcsigs==1.0.2
google-api-python-client==1.5.1
httplib2==0.10.3
mock==2.0.0
nose-parameterized==0.5.0
oauth2client==2.2.0
pbr==3.0.1
pyasn1==0.2.3
pyasn1-modules==0.0.8
rsa==3.4.2
simplejson==3.13.2
six==1.10.0
uritemplate==0.6
waitress==1.0.2
WebOb==1.7.2
WebTest==2.0.23

and this is the lib folder: 

> __pycache__                               httplib2-0.10.3.dist-info     pyasn1_modules                  simplejson-3.13.2.dist-info
apiclient                                 oauth2client                  pyasn1_modules-0.0.8.dist-info  six-1.11.0.dist-info
google_api_python_client-1.5.1.dist-info  oauth2client-2.2.0.dist-info  rsa                             six.py
googleapiclient                           pyasn1                        rsa-3.4.2.dist-info             uritemplate
httplib2                                  pyasn1-0.2.3.dist-info        simplejson                      uritemplate-0.6.dist-info

After deploying i see still the same error!

**Comment by marcin-kolda** [comment]
It seems you're using Python 3 instead of Python 2.7, which is supported by GAE Standard environment.

Please check the following threads and try to use earlier version of pip:
* https://stackoverflow.com/questions/43724987/syntax-error-in-google-api-python-client
* https://stackoverflow.com/questions/44932468/cron-job-failing-with-firebase-in-google-cloud-app-engine
* https://stackoverflow.com/questions/17348513/httplib2-error-installing-python-twitter-on-mac-osx

**Comment by majidshokrolahi** [comment]
You are right! I have two version of Python, 2.7 and 3, but the default is 3. Thank you so much. It works now 👍   :)
